name: dailypulse
description: "Daily Pulse - Track your daily moods and emotions"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^6.0.3
  emoji_picker_flutter: ^4.3.0
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  easy_date_timeline: ^2.0.9
  provider: ^6.1.2
  connectivity_plus: ^6.1.2
  logger: ^2.6.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  analyzer: ^6.4.1
  flutter_native_splash:
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/splash_logo.png
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/splash_logo_android12.png
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.png"


