name: dailypulse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^6.0.3
  emoji_picker_flutter: ^4.3.0
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  easy_date_timeline: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
